name: Build Docker Container

on:
  push:
    branches:
      - main
      - master 

jobs:
  docker:
    runs-on: registry.access.redhat.com/ubi8/ubi:latestt
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vavhal.sagar@hotmail.com
          password: w3dne$D@Y@dm$
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: quantumcybertronics/quantumdock:RancherV01.0.0
